# SwiftLint Configuration for Fishbowl (Nouns on a Phone)

# Include all source files
included:
  - NounsOnAPhone
  - NounsOnAPhoneTests
  - NounsOnAPhoneUITests

# Exclude generated and external files
excluded:
  - Pods
  - .build
  - DerivedData
  - .swiftpm
  - build

# Rule Configuration
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - todo # Allow TODO comments for development
  - force_try # Allow force try in tests
  - function_body_length # Allow longer functions for complex game logic

# Customize rule parameters
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# Allow force unwrapping in tests
force_unwrapping:
  severity: warning

# Custom rules for game-specific patterns
custom_rules:
  # Ensure proper use of game state
  game_state_naming:
    name: "Game State Naming"
    regex: "var\\s+gameState\\s*:"
    message: "Use consistent gameState variable naming"
    severity: warning

  # Encourage use of manager pattern
  direct_property_access:
    name: "Direct Property Access"
    regex: "gameState\\.(team1Score|team2Score|currentRound|currentTeam|timeRemaining)"
    message: "Consider using manager properties (e.g., gameState.scoreManager.team1Score)"
    severity: warning

# Reporter type
reporter: "xcode"

# Analyze only changed files
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import 